Fix package VERSION detection
Signed-off-by: Marco Vedovati <mvedovati@suse.com>

diff --git a/kiwi_post_run b/kiwi_post_run
--- a/kiwi_post_run
+++ b/kiwi_post_run
@@ -79,8 +79,8 @@ fi
 
 # Check if VERSION was defined properly and validate it
 # VERSION for RPM package has to be decimal number separete with dots
-if ! [[ $VERSION =~ ^([0-9]+\.){0,2}(\*|[0-9]+)$ ]]; then
-    echo "Local build detected or wrong version format"
+if ! [[ $VERSION =~ ^([0-9]+\.){0,2}(\*|[0-9]+)[-~+] ]]; then
+    echo "ERROR: local build or wrong version format detected: $VERSION"
     # Just arbitrarily assign the version since we have nothing else
     # to go on.
     VERSION="1.0.0"
