Fix version detect again

diff --git a/kiwi_post_run b/kiwi_post_run
--- a/kiwi_post_run
+++ b/kiwi_post_run
@@ -78,12 +78,12 @@ if [ -z "$RELEASE" ]; then
 fi
 
 # Check if VERSION was defined properly and validate it
-# VERSION for RPM package has to be decimal number separete with dots
-if ! [[ $VERSION =~ ^([0-9]+\.){0,2}(\*|[0-9]+)[?-~+] ]]; then
-    echo "ERROR: local build or wrong version format detected: $VERSION"
-    # Just arbitrarily assign the version since we have nothing else
-    # to go on.
-    VERSION="1.0.0"
+# VERSION for RPM package has to be:
+# - 1 to 3 integer numbers (base 10), separated by a ".", optionally
+# followed by one of "-", "+", "~" and an arbitrary string.
+if ! [[ $VERSION =~ ^([0-9]+\.){0,2}(\*|[0-9]+)([-~+].+)?$ ]]; then
+    echo "ERROR: wrong RPM version format detected: \"$VERSION\""
+    exit 1
 fi
 
 echo "Name:        $PKG_NAME"
